In [2]:
import tensorflow as tf

tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
# print(tensor)
ohe = tf.constant([0,1,0])
# print(ohe)
out = tf.boolean_mask(tensor, ohe)

X = tf.random.uniform([28, 28, 3])
# print(X)

y_hat = tf.constant([[0.8, 0.2, 0.5, 0.2, 5.0], [0.8, 0.2, 0.5, 0.2, 5.0]]) 
print(y_hat)
Y = tf.constant([4, 1])

argmax = tf.cast(tf.argmax(y_hat, axis=1), Y.dtype)
argmax == Y

tf.Tensor(
[[0.8 0.2 0.5 0.2 5. ]
 [0.8 0.2 0.5 0.2 5. ]], shape=(2, 5), dtype=float32)


<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [3]:
# try auto gradient
x = tf.Variable(1.)

def f(x):
    return x**2 + 2*x - 5

with tf.GradientTape() as tape:
    y = f(x)


# y = f(x)

print (y)
print(tape.gradient(y,x))

tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


In [4]:
# multiplications - understand shapes

import tensorflow as tf

a = tf.constant([[1,2,3], 
                 [4,5,6]]) # (2,3)

b = tf.constant([[1,1,1], 
                 [1,1,1]]) # (2,3)

b1 = tf.reshape(b, [3,2]) #(3,2)

batch_a = tf.stack([a,a], axis=2) # (2,3,2)
batch_b = tf.stack([b,b*2], axis=0) # (2,2,3)

# print(batch_b)
# print(a,b,b1)

# tf.matmul(a,b1) # (2,2)
# tf.matmul(b1,a) # (3,3)

tf.matmul(batch_a, batch_b) # (2,3,3). Batch=2

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 2,  2,  2],
        [ 4,  4,  4],
        [ 6,  6,  6]],

       [[16, 16, 16],
        [20, 20, 20],
        [24, 24, 24]]])>