In [2]:
import numpy as np

In [3]:
# einsum - Einstein Summation (Sum of Products)

A = [1, 2, 3]
B = [4, 5, 6]

# 2 rules for 'LHS -> RHS'. Letters correspond to axis
# - repeated letters in LHS: are "compatible" (same or, one of them is 1). These are element-wise multiplied
# - dropped letters in RHS: elements are summed along the corresponding axis.


# np.inner(A,B) # 32 () scalar. aka dot product
# np.outer(A,B) #  shape (A_row, B_col)

np.einsum('i', A) # A
np.einsum('i->', A) # sum(A)
np.einsum('i,j', A, B)



array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [5]:
# Advanced Indexing

import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print ('Our array is:' )
print (x )
print( '\n' )

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
rows = np.array([0,0,3,3])
cols = np.array([0,2,0,2]) 

y = x[rows,cols] 
   
print ('The corner elements of this array are:' )
print (y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[ 0  2  9 11]


In [7]:
#lexsort
x = np.array([[1,2], [1,5], [5,1], [1,0], [1,5]])
# print (x[:,1])
idx = np.lexsort((x[:,1], x[:,0]))
print (idx)
print (x[idx])

# np.unique(x[idx], axis=0)

[3 0 1 4 2]
[[1 0]
 [1 2]
 [1 5]
 [1 5]
 [5 1]]


In [8]:
import operator
x = [[25,1,1], [2,2,22], [3,3,3], [43,3,3]]

max(x, key=operator.itemgetter(2))

[2, 2, 22]